checkout_context: verify the current branch when getting the remote
This has not been checked in daemon mode, leading to the confusing
message

    Error: branch "master" in "/home/chrisrust/tmp/xmlhub-daemon/"
    does not have a default remote set, you can't push because of that

when there was no master branch at all.

(Hmm, check just the existence of the branch would be more appropriate
locally, but in the larger scheme we want it to be checked out.)